services:
  bot:
    image: python:3.12-alpine
    container_name: lazy_lake_helper_bot
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    working_dir: /app
    command: ["/bin/sh", "-c", "source venv/bin/activate && python src/bot.py"]
